version: '3'
services:
    app:
        build: .
        container_name: lyrics-scraping-app
        restart: always
        volumes:
            - ./src:/var/www

    chrome:
        image: selenium/standalone-chrome:3.6.0-bromine
        volumes:
            - /dev/shm:/dev/shm
            - ./src/:/var/www/html
        ports:
            - "4444:4444"

    nginx:
        build: .docker/nginx
        container_name: lyrics-scraping-nginx
        restart: always
        tty: true
        ports:
            - "$HTTP_PORT:80"
        volumes:
            - ./src:/var/www
        depends_on:
            - app

networks:
    default:
        external:
            name: nginx-proxy